security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-
    access_decision_manager:
        strategy: affirmative
    encoders:
      AppBundle\Entity\User:
         algorithm: bcrypt
         cost: 12
    providers:
        
       users:
           entity:
               class: AppBundle\Entity\User
               property: username
               #users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            #provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            form_login:
               login_path: login
               check_path: login
             
               csrf_token_generator: security.csrf.token_manager
               default_target_path: /
            logout:
                path: logout   
                target: /

               
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
